# -----------------------------------app dettails-----------------------------------
name: e_commerce_app
description: "A new Flutter project."

publish_to: "none"

# -----------------------------------version and build number-----------------------------------
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# -----------------------------------dependencies-----------------------------------

dependencies:
  flutter:
    sdk: flutter

  # Utility packages
  http: ^1.3.0
  lottie: ^3.3.1
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.5
  smooth_page_indicator: ^1.2.1

  # icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.7.2
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # -----------------------------------lints-----------------------------------

  flutter_lints: ^5.0.0

#-----------------------------------flutter packages-----------------------------------
flutter:
  uses-material-design: true

  # -----------------------------------assets-----------------------------------
  assets:
    - assets/images/animations/
    - assets/images/onboarding_images/
    - assets/images/categories/
    - assets/images/promo/
    - assets/images/product/
    - assets/videos/
    - assets/fonts/
    - assets/icons/
    - assets/logos/
  # -----------------------------------fonts-----------------------------------
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/pacifico_regular.ttf
    - family: PassionsConflict
      fonts:
        - asset: assets/fonts/passions_conflict_regular.ttf
    - family: Robot
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
    - family: RobotMono
      fonts:
        - asset: assets/fonts/robotomono_regular.ttf
